version: '2.2'

services:
  rce-dind-host:
    image: docker:19.03-dind
    restart: on-failure
    privileged: true
    volumes: 
      - dind-client-certs:/certs/client/
    stop_grace_period: 10s
    mem_limit: 4G
    memswap_limit: 4G
    pids_limit: 16384
    ulimits: 
      nofile:
        soft: 16000
        hard: 16000

  caller-runner:
    build: 
      context: pwn/caller
      dockerfile: runner/Dockerfile
    restart: on-failure
    links:
      - rce-dind-host:docker
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - SERVICE_TIMEOUT=30
    depends_on: 
      - rce-dind-host
    volumes: 
      - dind-client-certs:/home/caller-runner/.docker/:ro
    ports:
      - 7703:31337
    stop_grace_period: 5s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 4096
    ulimits: 
      nofile:
        soft: 4000
        hard: 4000

  esoteric-runner:
    build: 
      context: misc/esoteric
      dockerfile: runner/Dockerfile
    restart: on-failure
    links:
      - rce-dind-host:docker
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - SERVICE_TIMEOUT=30
    depends_on: 
      - rce-dind-host
    volumes: 
      - dind-client-certs:/home/esoteric-runner/.docker/:ro
    ports:
      - 7704:31337
    stop_grace_period: 5s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 4096
    ulimits: 
      nofile:
        soft: 4000
        hard: 4000

volumes:
  dind-client-certs:
